version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=api-test-user
      - POSTGRES_PASSWORD=api-test-pass
      - POSTGRES_DB=api_test_db
    ports:
      - '5432:5432'
